# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_RDA) += \
	rda8810pl-orangepi-2g-iot.dtb \
	rda8810pl-orangepi-i96.dtb

dtb-$(CONFIG_ARCH_UNISOC) += \
	sc7727s-1h10.dtb \
	sc7727s-samsung-g318h.dtb
